name: "Build Inference Image"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mlops-inference

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: containers/inference

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set full image name
        run: |
          echo "FULL_IMAGE_NAME=936379345511.dkr.ecr.us-east-1.amazonaws.com/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Build, tag, and push (Docker manifest v2 - SageMaker compatible)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          IMAGE_URI_LATEST="$ECR_REGISTRY/${{ env.IMAGE_NAME }}:latest"
          docker build -f containers/inference/Dockerfile -t "$IMAGE_URI_LATEST" .
          docker push "$IMAGE_URI_LATEST"